### ISSUE TITLE
How to install and run GenKI/notebook/SERGIO.py ?

### ISSUE THREAD

**Issue by xukun-zhang** [yjgeno/GenKI#7]
How to install and run GenKI/notebook/SERGIO.py's environment? The use of scTenifoldpy (pip install scTenifoldpy) does not seem to match ogenki's environment.

**Comment by yjgeno** [comment]
Hi @xukun-zhang, can you show the error message? What blocked you from using it?

**Comment by xukun-zhang** [comment]
> Hi @xukun-zhang, can you show the error message? What blocked you from using it?

**Thank you very much for your reply. I first successfully executed Example.ipynb according to your tutorial. Next I'll try to execute notebook/SERGIO.py using the simulation data you mentioned. The "scTenifold" library is missing. Then I install with "pip install scTenifoldpy" and the following error occurs:**
### 
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
genki 0.0.1.dev0 requires matplotlib~=3.5.1, but you have matplotlib 3.4.3 which is incompatible.
genki 0.0.1.dev0 requires numpy>=1.21.6, but you have numpy 1.20.3 which is incompatible.
genki 0.0.1.dev0 requires pandas~=1.4.2, but you have pandas 1.2.5 which is incompatible.
genki 0.0.1.dev0 requires ray>=1.11.0, but you have ray 1.8.0 which is incompatible.
genki 0.0.1.dev0 requires scanpy==1.9.1, but you have scanpy 1.7.2 which is incompatible.
genki 0.0.1.dev0 requires scikit-learn>=1.0.2, but you have scikit-learn 0.24.2 which is incompatible.
genki 0.0.1.dev0 requires scipy~=1.8.0, but you have scipy 1.6.3 which is incompatible.
scikit-misc 0.3.1 requires numpy>=1.22.3, but you have numpy 1.20.3 which is incompatible.
zarr 2.18.0 requires numpy>=1.23, but you have numpy 1.20.3 which is incompatible.
```

**Comment by xukun-zhang** [comment]
**Could you give detailed instructions on how to execute "`GenKI/notebook/SERGIO.py`"? I've downloaded the simulation data I need.**
Thank you so much!

**Comment by xukun-zhang** [comment]
This problem has been solved, thank you!
